# Generated by Django 5.1.7 on 2026-02-04 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_reel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reel',
        ),
    ]
